export interface PokemonInput {
    NationalNumber: number;
    Name: string;
    Tier: Tier;
    PrimaryType: string;
    SecondaryType: string | null;
    HP: number;
    Attack: number;
    Defense: number;
    SpecialAttack: number;
    SpecialDefense: number;
    Speed: number;
    PreEvolution: string | null;
    DefaultGender: string;
    FirstStage: number;
}

export const AllPokemon: PokemonInput[] = [
    {
        NationalNumber: 1,
        Name: "Bulbasaur",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 45,
        Attack: 49,
        Defense: 49,
        SpecialAttack: 65,
        SpecialDefense: 65,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 1
    },
    {
        NationalNumber: 2,
        Name: "Ivysaur",
        Tier: "NFE",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 60,
        Attack: 62,
        Defense: 63,
        SpecialAttack: 80,
        SpecialDefense: 80,
        Speed: 60,
        PreEvolution: "Bulbasaur",
        DefaultGender: "Random",
        FirstStage: 1
    },
    {
        NationalNumber: 3,
        Name: "Venusaur",
        Tier: "UUBL",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 80,
        Attack: 82,
        Defense: 83,
        SpecialAttack: 100,
        SpecialDefense: 100,
        Speed: 80,
        PreEvolution: "Ivysaur",
        DefaultGender: "Random",
        FirstStage: 1
    },
    {
        NationalNumber: 4,
        Name: "Charmander",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 39,
        Attack: 52,
        Defense: 43,
        SpecialAttack: 60,
        SpecialDefense: 50,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 4
    },
    {
        NationalNumber: 5,
        Name: "Charmeleon",
        Tier: "NFE",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 58,
        Attack: 64,
        Defense: 58,
        SpecialAttack: 80,
        SpecialDefense: 65,
        Speed: 80,
        PreEvolution: "Charmander",
        DefaultGender: "Random",
        FirstStage: 4
    },
    {
        NationalNumber: 6,
        Name: "Charizard",
        Tier: "UUBL",
        PrimaryType: "Fire",
        SecondaryType: "Flying",
        HP: 78,
        Attack: 84,
        Defense: 78,
        SpecialAttack: 109,
        SpecialDefense: 85,
        Speed: 100,
        PreEvolution: "Charmeleon",
        DefaultGender: "Random",
        FirstStage: 4
    },
    {
        NationalNumber: 7,
        Name: "Squirtle",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 44,
        Attack: 48,
        Defense: 65,
        SpecialAttack: 50,
        SpecialDefense: 64,
        Speed: 43,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 7
    },
    {
        NationalNumber: 8,
        Name: "Wartortle",
        Tier: "NFE",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 59,
        Attack: 63,
        Defense: 80,
        SpecialAttack: 65,
        SpecialDefense: 80,
        Speed: 58,
        PreEvolution: "Squirtle",
        DefaultGender: "Random",
        FirstStage: 7
    },
    {
        NationalNumber: 9,
        Name: "Blastoise",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 79,
        Attack: 83,
        Defense: 100,
        SpecialAttack: 85,
        SpecialDefense: 105,
        Speed: 78,
        PreEvolution: "Wartortle",
        DefaultGender: "Random",
        FirstStage: 7
    },
    {
        NationalNumber: 10,
        Name: "Caterpie",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: null,
        HP: 45,
        Attack: 30,
        Defense: 35,
        SpecialAttack: 20,
        SpecialDefense: 20,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 10
    },
    {
        NationalNumber: 11,
        Name: "Metapod",
        Tier: "NFE",
        PrimaryType: "Bug",
        SecondaryType: null,
        HP: 50,
        Attack: 20,
        Defense: 55,
        SpecialAttack: 25,
        SpecialDefense: 25,
        Speed: 30,
        PreEvolution: "Caterpie",
        DefaultGender: "Random",
        FirstStage: 10
    },
    {
        NationalNumber: 12,
        Name: "Butterfree",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Flying",
        HP: 60,
        Attack: 45,
        Defense: 50,
        SpecialAttack: 90,
        SpecialDefense: 80,
        Speed: 70,
        PreEvolution: "Metapod",
        DefaultGender: "Random",
        FirstStage: 10
    },
    {
        NationalNumber: 13,
        Name: "Weedle",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 40,
        Attack: 35,
        Defense: 30,
        SpecialAttack: 20,
        SpecialDefense: 20,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 13
    },
    {
        NationalNumber: 14,
        Name: "Kakuna",
        Tier: "NFE",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 45,
        Attack: 25,
        Defense: 50,
        SpecialAttack: 25,
        SpecialDefense: 25,
        Speed: 35,
        PreEvolution: "Weedle",
        DefaultGender: "Random",
        FirstStage: 13
    },
    {
        NationalNumber: 15,
        Name: "Beedrill",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 65,
        Attack: 90,
        Defense: 40,
        SpecialAttack: 45,
        SpecialDefense: 80,
        Speed: 75,
        PreEvolution: "Kakuna",
        DefaultGender: "Random",
        FirstStage: 13
    },
    {
        NationalNumber: 16,
        Name: "Pidgey",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 40,
        Attack: 45,
        Defense: 40,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 56,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 16
    },
    {
        NationalNumber: 17,
        Name: "Pidgeotto",
        Tier: "NFE",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 63,
        Attack: 60,
        Defense: 55,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 71,
        PreEvolution: "Pidgey",
        DefaultGender: "Random",
        FirstStage: 16
    },
    {
        NationalNumber: 18,
        Name: "Pidgeot",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 83,
        Attack: 80,
        Defense: 75,
        SpecialAttack: 70,
        SpecialDefense: 70,
        Speed: 101,
        PreEvolution: "Pidgeotto",
        DefaultGender: "Random",
        FirstStage: 16
    },
    {
        NationalNumber: 19,
        Name: "Rattata",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 30,
        Attack: 56,
        Defense: 35,
        SpecialAttack: 25,
        SpecialDefense: 35,
        Speed: 72,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 19
    },
    {
        NationalNumber: 20,
        Name: "Raticate",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 55,
        Attack: 81,
        Defense: 60,
        SpecialAttack: 50,
        SpecialDefense: 70,
        Speed: 97,
        PreEvolution: "Rattata",
        DefaultGender: "Random",
        FirstStage: 19
    },
    {
        NationalNumber: 21,
        Name: "Spearow",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 40,
        Attack: 60,
        Defense: 30,
        SpecialAttack: 31,
        SpecialDefense: 31,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 21
    },
    {
        NationalNumber: 22,
        Name: "Fearow",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 90,
        Defense: 65,
        SpecialAttack: 61,
        SpecialDefense: 61,
        Speed: 100,
        PreEvolution: "Spearow",
        DefaultGender: "Random",
        FirstStage: 21
    },
    {
        NationalNumber: 23,
        Name: "Ekans",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 35,
        Attack: 60,
        Defense: 44,
        SpecialAttack: 40,
        SpecialDefense: 54,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 23
    },
    {
        NationalNumber: 24,
        Name: "Arbok",
        Tier: "NU",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 60,
        Attack: 85,
        Defense: 69,
        SpecialAttack: 65,
        SpecialDefense: 79,
        Speed: 80,
        PreEvolution: "Ekans",
        DefaultGender: "Random",
        FirstStage: 23
    },
    {
        NationalNumber: 25,
        Name: "Pikachu",
        Tier: "UU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 35,
        Attack: 55,
        Defense: 40,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 90,
        PreEvolution: "Pichu",
        DefaultGender: "Random",
        FirstStage: 172
    },
    {
        NationalNumber: 26,
        Name: "Raichu",
        Tier: "NUBL",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 60,
        Attack: 90,
        Defense: 55,
        SpecialAttack: 90,
        SpecialDefense: 80,
        Speed: 110,
        PreEvolution: "Pikachu",
        DefaultGender: "Random",
        FirstStage: 172
    },
    {
        NationalNumber: 27,
        Name: "Sandshrew",
        Tier: "LC",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 50,
        Attack: 75,
        Defense: 85,
        SpecialAttack: 20,
        SpecialDefense: 30,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 27
    },
    {
        NationalNumber: 28,
        Name: "Sandslash",
        Tier: "UU",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 75,
        Attack: 100,
        Defense: 110,
        SpecialAttack: 45,
        SpecialDefense: 55,
        Speed: 65,
        PreEvolution: "Sandshrew",
        DefaultGender: "Random",
        FirstStage: 27
    },
    {
        NationalNumber: 29,
        Name: "Nidoran♀",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 55,
        Attack: 47,
        Defense: 52,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 41,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 29
    },
    {
        NationalNumber: 30,
        Name: "Nidorina",
        Tier: "NFE",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 70,
        Attack: 62,
        Defense: 67,
        SpecialAttack: 55,
        SpecialDefense: 55,
        Speed: 56,
        PreEvolution: "Nidoran♀",
        DefaultGender: "Random",
        FirstStage: 29
    },
    {
        NationalNumber: 31,
        Name: "Nidoqueen",
        Tier: "UU",
        PrimaryType: "Poison",
        SecondaryType: "Ground",
        HP: 90,
        Attack: 92,
        Defense: 87,
        SpecialAttack: 75,
        SpecialDefense: 85,
        Speed: 76,
        PreEvolution: "Nidorina",
        DefaultGender: "Random",
        FirstStage: 29
    },
    {
        NationalNumber: 32,
        Name: "Nidoran♂",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 46,
        Attack: 57,
        Defense: 40,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 32
    },
    {
        NationalNumber: 33,
        Name: "Nidorino",
        Tier: "NFE",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 61,
        Attack: 72,
        Defense: 57,
        SpecialAttack: 55,
        SpecialDefense: 55,
        Speed: 65,
        PreEvolution: "Nidoran♂",
        DefaultGender: "Random",
        FirstStage: 32
    },
    {
        NationalNumber: 34,
        Name: "Nidoking",
        Tier: "OU",
        PrimaryType: "Poison",
        SecondaryType: "Ground",
        HP: 81,
        Attack: 102,
        Defense: 77,
        SpecialAttack: 85,
        SpecialDefense: 75,
        Speed: 85,
        PreEvolution: "Nidorino",
        DefaultGender: "Random",
        FirstStage: 32
    },
    {
        NationalNumber: 35,
        Name: "Clefairy",
        Tier: "NFE",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 70,
        Attack: 45,
        Defense: 48,
        SpecialAttack: 60,
        SpecialDefense: 65,
        Speed: 35,
        PreEvolution: "Cleffa",
        DefaultGender: "Random",
        FirstStage: 173
    },
    {
        NationalNumber: 36,
        Name: "Clefable",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 95,
        Attack: 70,
        Defense: 73,
        SpecialAttack: 95,
        SpecialDefense: 90,
        Speed: 60,
        PreEvolution: "Clefairy",
        DefaultGender: "Random",
        FirstStage: 173
    },
    {
        NationalNumber: 37,
        Name: "Vulpix",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 38,
        Attack: 41,
        Defense: 40,
        SpecialAttack: 50,
        SpecialDefense: 65,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 37
    },
    {
        NationalNumber: 38,
        Name: "Ninetales",
        Tier: "NU",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 73,
        Attack: 76,
        Defense: 75,
        SpecialAttack: 81,
        SpecialDefense: 100,
        Speed: 100,
        PreEvolution: "Vulpix",
        DefaultGender: "Random",
        FirstStage: 37
    },
    {
        NationalNumber: 39,
        Name: "Jigglypuff",
        Tier: "NFE",
        PrimaryType: "Normal",
        SecondaryType: "Normal",
        HP: 115,
        Attack: 45,
        Defense: 20,
        SpecialAttack: 45,
        SpecialDefense: 25,
        Speed: 20,
        PreEvolution: "Igglybuff",
        DefaultGender: "Random",
        FirstStage: 174
    },
    {
        NationalNumber: 40,
        Name: "Wigglytuff",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Normal",
        HP: 140,
        Attack: 70,
        Defense: 45,
        SpecialAttack: 85,
        SpecialDefense: 50,
        Speed: 45,
        PreEvolution: "Jigglypuff",
        DefaultGender: "Random",
        FirstStage: 174
    },
    {
        NationalNumber: 41,
        Name: "Zubat",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: "Flying",
        HP: 40,
        Attack: 45,
        Defense: 35,
        SpecialAttack: 30,
        SpecialDefense: 40,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 41
    },
    {
        NationalNumber: 42,
        Name: "Golbat",
        Tier: "NFE",
        PrimaryType: "Poison",
        SecondaryType: "Flying",
        HP: 75,
        Attack: 80,
        Defense: 70,
        SpecialAttack: 65,
        SpecialDefense: 75,
        Speed: 90,
        PreEvolution: "Zubat",
        DefaultGender: "Random",
        FirstStage: 41
    },
    {
        NationalNumber: 43,
        Name: "Oddish",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 45,
        Attack: 50,
        Defense: 55,
        SpecialAttack: 75,
        SpecialDefense: 65,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 43
    },
    {
        NationalNumber: 44,
        Name: "Gloom",
        Tier: "NU",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 60,
        Attack: 65,
        Defense: 70,
        SpecialAttack: 85,
        SpecialDefense: 75,
        Speed: 40,
        PreEvolution: "Oddish",
        DefaultGender: "Random",
        FirstStage: 43
    },
    {
        NationalNumber: 45,
        Name: "Vileplume",
        Tier: "UU",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 75,
        Attack: 80,
        Defense: 85,
        SpecialAttack: 110,
        SpecialDefense: 90,
        Speed: 50,
        PreEvolution: "Gloom",
        DefaultGender: "Random",
        FirstStage: 43
    },
    {
        NationalNumber: 46,
        Name: "Paras",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: "Grass",
        HP: 35,
        Attack: 70,
        Defense: 55,
        SpecialAttack: 45,
        SpecialDefense: 55,
        Speed: 25,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 46
    },
    {
        NationalNumber: 47,
        Name: "Parasect",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Grass",
        HP: 60,
        Attack: 95,
        Defense: 80,
        SpecialAttack: 60,
        SpecialDefense: 80,
        Speed: 30,
        PreEvolution: "Paras",
        DefaultGender: "Random",
        FirstStage: 46
    },
    {
        NationalNumber: 48,
        Name: "Venonat",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 60,
        Attack: 55,
        Defense: 50,
        SpecialAttack: 40,
        SpecialDefense: 55,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 48
    },
    {
        NationalNumber: 49,
        Name: "Venomoth",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 70,
        Attack: 65,
        Defense: 60,
        SpecialAttack: 90,
        SpecialDefense: 75,
        Speed: 90,
        PreEvolution: "Venonat",
        DefaultGender: "Random",
        FirstStage: 48
    },
    {
        NationalNumber: 50,
        Name: "Diglett",
        Tier: "LC",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 10,
        Attack: 55,
        Defense: 25,
        SpecialAttack: 35,
        SpecialDefense: 45,
        Speed: 95,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 50
    },
    {
        NationalNumber: 51,
        Name: "Dugtrio",
        Tier: "NU",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 35,
        Attack: 80,
        Defense: 50,
        SpecialAttack: 50,
        SpecialDefense: 70,
        Speed: 120,
        PreEvolution: "Diglett",
        DefaultGender: "Random",
        FirstStage: 50
    },
    {
        NationalNumber: 52,
        Name: "Meowth",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 40,
        Attack: 45,
        Defense: 35,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 52
    },
    {
        NationalNumber: 53,
        Name: "Persian",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 65,
        Attack: 70,
        Defense: 60,
        SpecialAttack: 65,
        SpecialDefense: 65,
        Speed: 115,
        PreEvolution: "Meowth",
        DefaultGender: "Random",
        FirstStage: 52
    },
    {
        NationalNumber: 54,
        Name: "Psyduck",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 50,
        Attack: 52,
        Defense: 48,
        SpecialAttack: 65,
        SpecialDefense: 50,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 54
    },
    {
        NationalNumber: 55,
        Name: "Golduck",
        Tier: "NUBL",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 80,
        Attack: 82,
        Defense: 78,
        SpecialAttack: 95,
        SpecialDefense: 80,
        Speed: 85,
        PreEvolution: "Psyduck",
        DefaultGender: "Random",
        FirstStage: 54
    },
    {
        NationalNumber: 56,
        Name: "Mankey",
        Tier: "LC",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 40,
        Attack: 80,
        Defense: 35,
        SpecialAttack: 35,
        SpecialDefense: 45,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 56
    },
    {
        NationalNumber: 57,
        Name: "Primeape",
        Tier: "NU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 65,
        Attack: 105,
        Defense: 60,
        SpecialAttack: 60,
        SpecialDefense: 70,
        Speed: 95,
        PreEvolution: "Mankey",
        DefaultGender: "Random",
        FirstStage: 56
    },
    {
        NationalNumber: 58,
        Name: "Growlithe",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 55,
        Attack: 70,
        Defense: 45,
        SpecialAttack: 70,
        SpecialDefense: 50,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 58
    },
    {
        NationalNumber: 59,
        Name: "Arcanine",
        Tier: "UU",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 90,
        Attack: 110,
        Defense: 80,
        SpecialAttack: 100,
        SpecialDefense: 80,
        Speed: 95,
        PreEvolution: "Growlithe",
        DefaultGender: "Random",
        FirstStage: 58
    },
    {
        NationalNumber: 60,
        Name: "Poliwag",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 40,
        Attack: 50,
        Defense: 40,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 60
    },
    {
        NationalNumber: 61,
        Name: "Poliwhirl",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 65,
        Attack: 65,
        Defense: 65,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 90,
        PreEvolution: "Poliwag",
        DefaultGender: "Random",
        FirstStage: 60
    },
    {
        NationalNumber: 62,
        Name: "Poliwrath",
        Tier: "NUBL",
        PrimaryType: "Water",
        SecondaryType: "Fighting",
        HP: 90,
        Attack: 95,
        Defense: 95,
        SpecialAttack: 70,
        SpecialDefense: 90,
        Speed: 70,
        PreEvolution: "Poliwhirl",
        DefaultGender: "Random",
        FirstStage: 60
    },
    {
        NationalNumber: 63,
        Name: "Abra",
        Tier: "LC",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 25,
        Attack: 20,
        Defense: 15,
        SpecialAttack: 105,
        SpecialDefense: 55,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 63
    },
    {
        NationalNumber: 64,
        Name: "Kadabra",
        Tier: "UU",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 40,
        Attack: 35,
        Defense: 30,
        SpecialAttack: 120,
        SpecialDefense: 70,
        Speed: 105,
        PreEvolution: "Abra",
        DefaultGender: "Random",
        FirstStage: 63
    },
    {
        NationalNumber: 65,
        Name: "Alakazam",
        Tier: "UUBL",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 55,
        Attack: 50,
        Defense: 45,
        SpecialAttack: 135,
        SpecialDefense: 95,
        Speed: 120,
        PreEvolution: "Kadabra",
        DefaultGender: "Random",
        FirstStage: 63
    },
    {
        NationalNumber: 66,
        Name: "Machop",
        Tier: "LC",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 70,
        Attack: 80,
        Defense: 50,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 66
    },
    {
        NationalNumber: 67,
        Name: "Machoke",
        Tier: "NU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 80,
        Attack: 100,
        Defense: 70,
        SpecialAttack: 50,
        SpecialDefense: 60,
        Speed: 45,
        PreEvolution: "Machop",
        DefaultGender: "Random",
        FirstStage: 66
    },
    {
        NationalNumber: 68,
        Name: "Machamp",
        Tier: "OU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 90,
        Attack: 130,
        Defense: 80,
        SpecialAttack: 65,
        SpecialDefense: 85,
        Speed: 55,
        PreEvolution: "Machoke",
        DefaultGender: "Random",
        FirstStage: 66
    },
    {
        NationalNumber: 69,
        Name: "Bellsprout",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 50,
        Attack: 75,
        Defense: 35,
        SpecialAttack: 70,
        SpecialDefense: 30,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 69
    },
    {
        NationalNumber: 70,
        Name: "Weepinbell",
        Tier: "NFE",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 65,
        Attack: 90,
        Defense: 50,
        SpecialAttack: 85,
        SpecialDefense: 45,
        Speed: 55,
        PreEvolution: "Bellsprout",
        DefaultGender: "Random",
        FirstStage: 69
    },
    {
        NationalNumber: 71,
        Name: "Victreebel",
        Tier: "UU",
        PrimaryType: "Grass",
        SecondaryType: "Poison",
        HP: 80,
        Attack: 105,
        Defense: 65,
        SpecialAttack: 100,
        SpecialDefense: 70,
        Speed: 70,
        PreEvolution: "Weepinbell",
        DefaultGender: "Random",
        FirstStage: 69
    },
    {
        NationalNumber: 72,
        Name: "Tentacool",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Poison",
        HP: 40,
        Attack: 40,
        Defense: 35,
        SpecialAttack: 50,
        SpecialDefense: 100,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 72
    },
    {
        NationalNumber: 73,
        Name: "Tentacruel",
        Tier: "UUBL",
        PrimaryType: "Water",
        SecondaryType: "Poison",
        HP: 80,
        Attack: 70,
        Defense: 65,
        SpecialAttack: 80,
        SpecialDefense: 120,
        Speed: 100,
        PreEvolution: "Tentacool",
        DefaultGender: "Random",
        FirstStage: 72
    },
    {
        NationalNumber: 74,
        Name: "Geodude",
        Tier: "LC",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 40,
        Attack: 80,
        Defense: 100,
        SpecialAttack: 30,
        SpecialDefense: 30,
        Speed: 20,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 74
    },
    {
        NationalNumber: 75,
        Name: "Graveler",
        Tier: "NU",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 55,
        Attack: 95,
        Defense: 115,
        SpecialAttack: 45,
        SpecialDefense: 45,
        Speed: 35,
        PreEvolution: "Geodude",
        DefaultGender: "Random",
        FirstStage: 74
    },
    {
        NationalNumber: 76,
        Name: "Golem",
        Tier: "OU",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 80,
        Attack: 120,
        Defense: 130,
        SpecialAttack: 55,
        SpecialDefense: 65,
        Speed: 45,
        PreEvolution: "Graveler",
        DefaultGender: "Random",
        FirstStage: 74
    },
    {
        NationalNumber: 77,
        Name: "Ponyta",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 50,
        Attack: 85,
        Defense: 55,
        SpecialAttack: 65,
        SpecialDefense: 65,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 77
    },
    {
        NationalNumber: 78,
        Name: "Rapidash",
        Tier: "NU",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 65,
        Attack: 100,
        Defense: 70,
        SpecialAttack: 80,
        SpecialDefense: 80,
        Speed: 105,
        PreEvolution: "Ponyta",
        DefaultGender: "Random",
        FirstStage: 77
    },
    {
        NationalNumber: 79,
        Name: "Slowpoke",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Psychic",
        HP: 90,
        Attack: 65,
        Defense: 65,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 15,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 79
    },
    {
        NationalNumber: 80,
        Name: "Slowbro",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Psychic",
        HP: 95,
        Attack: 75,
        Defense: 110,
        SpecialAttack: 100,
        SpecialDefense: 80,
        Speed: 30,
        PreEvolution: "Slowpoke",
        DefaultGender: "Random",
        FirstStage: 79
    },
    {
        NationalNumber: 81,
        Name: "Magnemite",
        Tier: "NU",
        PrimaryType: "Electric",
        SecondaryType: "Steel",
        HP: 25,
        Attack: 35,
        Defense: 70,
        SpecialAttack: 95,
        SpecialDefense: 55,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 81
    },
    {
        NationalNumber: 82,
        Name: "Magneton",
        Tier: "UU",
        PrimaryType: "Electric",
        SecondaryType: "Steel",
        HP: 50,
        Attack: 60,
        Defense: 95,
        SpecialAttack: 120,
        SpecialDefense: 70,
        Speed: 70,
        PreEvolution: "Magnemite",
        DefaultGender: "Genderless",
        FirstStage: 81
    },
    {
        NationalNumber: 83,
        Name: "Farfetch'd",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 52,
        Attack: 65,
        Defense: 55,
        SpecialAttack: 58,
        SpecialDefense: 62,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 83
    },
    {
        NationalNumber: 84,
        Name: "Doduo",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 35,
        Attack: 85,
        Defense: 45,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 75,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 84
    },
    {
        NationalNumber: 85,
        Name: "Dodrio",
        Tier: "UU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 60,
        Attack: 110,
        Defense: 70,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 100,
        PreEvolution: "Doduo",
        DefaultGender: "Random",
        FirstStage: 84
    },
    {
        NationalNumber: 86,
        Name: "Seel",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 65,
        Attack: 45,
        Defense: 55,
        SpecialAttack: 45,
        SpecialDefense: 70,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 86
    },
    {
        NationalNumber: 87,
        Name: "Dewgong",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Ice",
        HP: 90,
        Attack: 70,
        Defense: 80,
        SpecialAttack: 70,
        SpecialDefense: 95,
        Speed: 70,
        PreEvolution: "Seel",
        DefaultGender: "Random",
        FirstStage: 86
    },
    {
        NationalNumber: 88,
        Name: "Grimer",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 80,
        Attack: 80,
        Defense: 50,
        SpecialAttack: 40,
        SpecialDefense: 50,
        Speed: 25,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 88
    },
    {
        NationalNumber: 89,
        Name: "Muk",
        Tier: "UUBL",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 105,
        Attack: 105,
        Defense: 75,
        SpecialAttack: 65,
        SpecialDefense: 100,
        Speed: 50,
        PreEvolution: "Grimer",
        DefaultGender: "Random",
        FirstStage: 88
    },
    {
        NationalNumber: 90,
        Name: "Shellder",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 30,
        Attack: 65,
        Defense: 100,
        SpecialAttack: 45,
        SpecialDefense: 25,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 90
    },
    {
        NationalNumber: 91,
        Name: "Cloyster",
        Tier: "OU",
        PrimaryType: "Water",
        SecondaryType: "Ice",
        HP: 50,
        Attack: 95,
        Defense: 180,
        SpecialAttack: 85,
        SpecialDefense: 45,
        Speed: 70,
        PreEvolution: "Shellder",
        DefaultGender: "Random",
        FirstStage: 90
    },
    {
        NationalNumber: 92,
        Name: "Gastly",
        Tier: "NU",
        PrimaryType: "Ghost",
        SecondaryType: "Poison",
        HP: 30,
        Attack: 35,
        Defense: 30,
        SpecialAttack: 100,
        SpecialDefense: 35,
        Speed: 80,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 92
    },
    {
        NationalNumber: 93,
        Name: "Haunter",
        Tier: "UU",
        PrimaryType: "Ghost",
        SecondaryType: "Poison",
        HP: 45,
        Attack: 50,
        Defense: 45,
        SpecialAttack: 115,
        SpecialDefense: 55,
        Speed: 95,
        PreEvolution: "Gastly",
        DefaultGender: "Random",
        FirstStage: 92
    },
    {
        NationalNumber: 94,
        Name: "Gengar",
        Tier: "OU",
        PrimaryType: "Ghost",
        SecondaryType: "Poison",
        HP: 60,
        Attack: 65,
        Defense: 60,
        SpecialAttack: 130,
        SpecialDefense: 75,
        Speed: 110,
        PreEvolution: "Haunter",
        DefaultGender: "Random",
        FirstStage: 92
    },
    {
        NationalNumber: 95,
        Name: "Onix",
        Tier: "LC",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 35,
        Attack: 45,
        Defense: 160,
        SpecialAttack: 30,
        SpecialDefense: 45,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 95
    },
    {
        NationalNumber: 96,
        Name: "Drowzee",
        Tier: "LC",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 60,
        Attack: 48,
        Defense: 45,
        SpecialAttack: 43,
        SpecialDefense: 90,
        Speed: 42,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 96
    },
    {
        NationalNumber: 97,
        Name: "Hypno",
        Tier: "UU",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 85,
        Attack: 73,
        Defense: 70,
        SpecialAttack: 73,
        SpecialDefense: 115,
        Speed: 67,
        PreEvolution: "Drowzee",
        DefaultGender: "Random",
        FirstStage: 96
    },
    {
        NationalNumber: 98,
        Name: "Krabby",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 30,
        Attack: 105,
        Defense: 90,
        SpecialAttack: 25,
        SpecialDefense: 25,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 98
    },
    {
        NationalNumber: 99,
        Name: "Kingler",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 55,
        Attack: 130,
        Defense: 115,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 75,
        PreEvolution: "Krabby",
        DefaultGender: "Random",
        FirstStage: 98
    },
    {
        NationalNumber: 100,
        Name: "Voltorb",
        Tier: "NU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 40,
        Attack: 30,
        Defense: 50,
        SpecialAttack: 55,
        SpecialDefense: 55,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 100
    },
    {
        NationalNumber: 101,
        Name: "Electrode",
        Tier: "UU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 60,
        Attack: 50,
        Defense: 70,
        SpecialAttack: 80,
        SpecialDefense: 80,
        Speed: 140,
        PreEvolution: "Voltorb",
        DefaultGender: "Genderless",
        FirstStage: 100
    },
    {
        NationalNumber: 102,
        Name: "Exeggcute",
        Tier: "NU",
        PrimaryType: "Grass",
        SecondaryType: "Psychic",
        HP: 60,
        Attack: 40,
        Defense: 80,
        SpecialAttack: 60,
        SpecialDefense: 45,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 102
    },
    {
        NationalNumber: 103,
        Name: "Exeggutor",
        Tier: "OU",
        PrimaryType: "Grass",
        SecondaryType: "Psychic",
        HP: 95,
        Attack: 95,
        Defense: 85,
        SpecialAttack: 125,
        SpecialDefense: 65,
        Speed: 55,
        PreEvolution: "Exeggcute",
        DefaultGender: "Random",
        FirstStage: 102
    },
    {
        NationalNumber: 104,
        Name: "Cubone",
        Tier: "NU",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 50,
        Attack: 50,
        Defense: 95,
        SpecialAttack: 40,
        SpecialDefense: 50,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 104
    },
    {
        NationalNumber: 105,
        Name: "Marowak",
        Tier: "OU",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 60,
        Attack: 80,
        Defense: 110,
        SpecialAttack: 50,
        SpecialDefense: 80,
        Speed: 45,
        PreEvolution: "Cubone",
        DefaultGender: "Random",
        FirstStage: 104
    },
    {
        NationalNumber: 106,
        Name: "Hitmonlee",
        Tier: "NU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 50,
        Attack: 120,
        Defense: 53,
        SpecialAttack: 35,
        SpecialDefense: 110,
        Speed: 87,
        PreEvolution: "Tyrogue",
        DefaultGender: "Male",
        FirstStage: 236
    },
    {
        NationalNumber: 107,
        Name: "Hitmonchan",
        Tier: "NU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 50,
        Attack: 105,
        Defense: 79,
        SpecialAttack: 35,
        SpecialDefense: 110,
        Speed: 76,
        PreEvolution: "Tyrogue",
        DefaultGender: "Male",
        FirstStage: 236
    },
    {
        NationalNumber: 108,
        Name: "Lickitung",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 90,
        Attack: 55,
        Defense: 75,
        SpecialAttack: 60,
        SpecialDefense: 75,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 108
    },
    {
        NationalNumber: 109,
        Name: "Koffing",
        Tier: "LC",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 40,
        Attack: 65,
        Defense: 95,
        SpecialAttack: 60,
        SpecialDefense: 45,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 109
    },
    {
        NationalNumber: 110,
        Name: "Weezing",
        Tier: "NU",
        PrimaryType: "Poison",
        SecondaryType: null,
        HP: 65,
        Attack: 90,
        Defense: 120,
        SpecialAttack: 85,
        SpecialDefense: 70,
        Speed: 60,
        PreEvolution: "Koffing",
        DefaultGender: "Random",
        FirstStage: 109
    },
    {
        NationalNumber: 111,
        Name: "Rhyhorn",
        Tier: "LC",
        PrimaryType: "Ground",
        SecondaryType: "Rock",
        HP: 80,
        Attack: 85,
        Defense: 95,
        SpecialAttack: 30,
        SpecialDefense: 30,
        Speed: 25,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 111
    },
    {
        NationalNumber: 112,
        Name: "Rhydon",
        Tier: "OU",
        PrimaryType: "Ground",
        SecondaryType: "Rock",
        HP: 105,
        Attack: 130,
        Defense: 120,
        SpecialAttack: 45,
        SpecialDefense: 45,
        Speed: 40,
        PreEvolution: "Rhyhorn",
        DefaultGender: "Random",
        FirstStage: 111
    },
    {
        NationalNumber: 113,
        Name: "Chansey",
        Tier: "UU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 250,
        Attack: 5,
        Defense: 5,
        SpecialAttack: 35,
        SpecialDefense: 105,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Female",
        FirstStage: 113
    },
    {
        NationalNumber: 114,
        Name: "Tangela",
        Tier: "NU",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 65,
        Attack: 55,
        Defense: 115,
        SpecialAttack: 100,
        SpecialDefense: 40,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 114
    },
    {
        NationalNumber: 115,
        Name: "Kangaskhan",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 105,
        Attack: 95,
        Defense: 80,
        SpecialAttack: 40,
        SpecialDefense: 80,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Female",
        FirstStage: 115
    },
    {
        NationalNumber: 116,
        Name: "Horsea",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 30,
        Attack: 40,
        Defense: 70,
        SpecialAttack: 70,
        SpecialDefense: 25,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 116
    },
    {
        NationalNumber: 117,
        Name: "Seadra",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 55,
        Attack: 65,
        Defense: 95,
        SpecialAttack: 95,
        SpecialDefense: 45,
        Speed: 85,
        PreEvolution: "Horsea",
        DefaultGender: "Random",
        FirstStage: 116
    },
    {
        NationalNumber: 118,
        Name: "Goldeen",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 45,
        Attack: 67,
        Defense: 60,
        SpecialAttack: 35,
        SpecialDefense: 50,
        Speed: 63,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 118
    },
    {
        NationalNumber: 119,
        Name: "Seaking",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 80,
        Attack: 92,
        Defense: 65,
        SpecialAttack: 65,
        SpecialDefense: 80,
        Speed: 68,
        PreEvolution: "Goldeen",
        DefaultGender: "Random",
        FirstStage: 118
    },
    {
        NationalNumber: 120,
        Name: "Staryu",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 30,
        Attack: 45,
        Defense: 55,
        SpecialAttack: 70,
        SpecialDefense: 55,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 120
    },
    {
        NationalNumber: 121,
        Name: "Starmie",
        Tier: "OU",
        PrimaryType: "Water",
        SecondaryType: "Psychic",
        HP: 60,
        Attack: 75,
        Defense: 85,
        SpecialAttack: 100,
        SpecialDefense: 85,
        Speed: 115,
        PreEvolution: "Staryu",
        DefaultGender: "Genderless",
        FirstStage: 120
    },
    {
        NationalNumber: 122,
        Name: "Mr. Mime",
        Tier: "UU",
        PrimaryType: "Psychic",
        SecondaryType: "Normal",
        HP: 40,
        Attack: 45,
        Defense: 65,
        SpecialAttack: 100,
        SpecialDefense: 120,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 122
    },
    {
        NationalNumber: 123,
        Name: "Scyther",
        Tier: "UU",
        PrimaryType: "Bug",
        SecondaryType: "Flying",
        HP: 70,
        Attack: 110,
        Defense: 80,
        SpecialAttack: 55,
        SpecialDefense: 80,
        Speed: 105,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 123
    },
    {
        NationalNumber: 124,
        Name: "Jynx",
        Tier: "OU",
        PrimaryType: "Ice",
        SecondaryType: "Psychic",
        HP: 65,
        Attack: 50,
        Defense: 35,
        SpecialAttack: 115,
        SpecialDefense: 95,
        Speed: 95,
        PreEvolution: "Smoochum",
        DefaultGender: "Female",
        FirstStage: 238
    },
    {
        NationalNumber: 125,
        Name: "Electabuzz",
        Tier: "UU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 65,
        Attack: 83,
        Defense: 57,
        SpecialAttack: 95,
        SpecialDefense: 85,
        Speed: 105,
        PreEvolution: "Elekid",
        DefaultGender: "Random",
        FirstStage: 239
    },
    {
        NationalNumber: 126,
        Name: "Magmar",
        Tier: "NU",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 65,
        Attack: 95,
        Defense: 57,
        SpecialAttack: 100,
        SpecialDefense: 85,
        Speed: 93,
        PreEvolution: "Magby",
        DefaultGender: "Random",
        FirstStage: 240
    },
    {
        NationalNumber: 127,
        Name: "Pinsir",
        Tier: "UU",
        PrimaryType: "Bug",
        SecondaryType: null,
        HP: 65,
        Attack: 125,
        Defense: 100,
        SpecialAttack: 55,
        SpecialDefense: 70,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 127
    },
    {
        NationalNumber: 128,
        Name: "Tauros",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 75,
        Attack: 100,
        Defense: 95,
        SpecialAttack: 40,
        SpecialDefense: 70,
        Speed: 110,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 128
    },
    {
        NationalNumber: 129,
        Name: "Magikarp",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 20,
        Attack: 10,
        Defense: 55,
        SpecialAttack: 15,
        SpecialDefense: 20,
        Speed: 80,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 129
    },
    {
        NationalNumber: 130,
        Name: "Gyarados",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Flying",
        HP: 95,
        Attack: 125,
        Defense: 79,
        SpecialAttack: 60,
        SpecialDefense: 100,
        Speed: 81,
        PreEvolution: "Magikarp",
        DefaultGender: "Random",
        FirstStage: 129
    },
    {
        NationalNumber: 131,
        Name: "Lapras",
        Tier: "UUBL",
        PrimaryType: "Water",
        SecondaryType: "Ice",
        HP: 130,
        Attack: 85,
        Defense: 80,
        SpecialAttack: 85,
        SpecialDefense: 95,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 131
    },
    {
        NationalNumber: 132,
        Name: "Ditto",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 48,
        Attack: 48,
        Defense: 48,
        SpecialAttack: 48,
        SpecialDefense: 48,
        Speed: 48,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 132
    },
    {
        NationalNumber: 133,
        Name: "Eevee",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 55,
        Attack: 55,
        Defense: 50,
        SpecialAttack: 45,
        SpecialDefense: 65,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 134,
        Name: "Vaporeon",
        Tier: "OU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 130,
        Attack: 65,
        Defense: 60,
        SpecialAttack: 110,
        SpecialDefense: 95,
        Speed: 65,
        PreEvolution: "Eevee",
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 135,
        Name: "Jolteon",
        Tier: "UUBL",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 65,
        Attack: 65,
        Defense: 60,
        SpecialAttack: 110,
        SpecialDefense: 95,
        Speed: 130,
        PreEvolution: "Eevee",
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 136,
        Name: "Flareon",
        Tier: "NU",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 65,
        Attack: 130,
        Defense: 60,
        SpecialAttack: 95,
        SpecialDefense: 110,
        Speed: 65,
        PreEvolution: "Eevee",
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 137,
        Name: "Porygon",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 65,
        Attack: 60,
        Defense: 70,
        SpecialAttack: 85,
        SpecialDefense: 75,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 137
    },
    {
        NationalNumber: 138,
        Name: "Omanyte",
        Tier: "LC",
        PrimaryType: "Rock",
        SecondaryType: "Water",
        HP: 35,
        Attack: 40,
        Defense: 100,
        SpecialAttack: 90,
        SpecialDefense: 55,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 138
    },
    {
        NationalNumber: 139,
        Name: "Omastar",
        Tier: "UU",
        PrimaryType: "Rock",
        SecondaryType: "Water",
        HP: 70,
        Attack: 60,
        Defense: 125,
        SpecialAttack: 115,
        SpecialDefense: 70,
        Speed: 55,
        PreEvolution: "Omanyte",
        DefaultGender: "Random",
        FirstStage: 138
    },
    {
        NationalNumber: 140,
        Name: "Kabuto",
        Tier: "LC",
        PrimaryType: "Rock",
        SecondaryType: "Water",
        HP: 30,
        Attack: 80,
        Defense: 90,
        SpecialAttack: 55,
        SpecialDefense: 45,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 140
    },
    {
        NationalNumber: 141,
        Name: "Kabutops",
        Tier: "UU",
        PrimaryType: "Rock",
        SecondaryType: "Water",
        HP: 60,
        Attack: 115,
        Defense: 105,
        SpecialAttack: 65,
        SpecialDefense: 70,
        Speed: 80,
        PreEvolution: "Kabuto",
        DefaultGender: "Random",
        FirstStage: 140
    },
    {
        NationalNumber: 142,
        Name: "Aerodactyl",
        Tier: "UUBL",
        PrimaryType: "Rock",
        SecondaryType: "Flying",
        HP: 80,
        Attack: 105,
        Defense: 65,
        SpecialAttack: 60,
        SpecialDefense: 75,
        Speed: 130,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 142
    },
    {
        NationalNumber: 143,
        Name: "Snorlax",
        Tier: "OU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 160,
        Attack: 110,
        Defense: 65,
        SpecialAttack: 65,
        SpecialDefense: 110,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 143
    },
    {
        NationalNumber: 144,
        Name: "Articuno",
        Tier: "UUBL",
        PrimaryType: "Ice",
        SecondaryType: "Flying",
        HP: 90,
        Attack: 85,
        Defense: 100,
        SpecialAttack: 95,
        SpecialDefense: 125,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 144
    },
    {
        NationalNumber: 145,
        Name: "Zapdos",
        Tier: "OU",
        PrimaryType: "Electric",
        SecondaryType: "Flying",
        HP: 90,
        Attack: 90,
        Defense: 85,
        SpecialAttack: 125,
        SpecialDefense: 90,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 145
    },
    {
        NationalNumber: 146,
        Name: "Moltres",
        Tier: "UUBL",
        PrimaryType: "Fire",
        SecondaryType: "Flying",
        HP: 90,
        Attack: 100,
        Defense: 90,
        SpecialAttack: 125,
        SpecialDefense: 85,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 146
    },
    {
        NationalNumber: 147,
        Name: "Dratini",
        Tier: "LC",
        PrimaryType: "Dragon",
        SecondaryType: null,
        HP: 41,
        Attack: 64,
        Defense: 45,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 147
    },
    {
        NationalNumber: 148,
        Name: "Dragonair",
        Tier: "NU",
        PrimaryType: "Dragon",
        SecondaryType: null,
        HP: 61,
        Attack: 84,
        Defense: 65,
        SpecialAttack: 70,
        SpecialDefense: 70,
        Speed: 70,
        PreEvolution: "Dratini",
        DefaultGender: "Random",
        FirstStage: 147
    },
    {
        NationalNumber: 149,
        Name: "Dragonite",
        Tier: "UUBL",
        PrimaryType: "Dragon",
        SecondaryType: "Flying",
        HP: 91,
        Attack: 134,
        Defense: 95,
        SpecialAttack: 100,
        SpecialDefense: 100,
        Speed: 80,
        PreEvolution: "Dragonair",
        DefaultGender: "Random",
        FirstStage: 147
    },
    {
        NationalNumber: 150,
        Name: "Mewtwo",
        Tier: "Uber",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 106,
        Attack: 110,
        Defense: 90,
        SpecialAttack: 154,
        SpecialDefense: 90,
        Speed: 130,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 150
    },
    {
        NationalNumber: 151,
        Name: "Mew",
        Tier: "Uber",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 100,
        Attack: 100,
        Defense: 100,
        SpecialAttack: 100,
        SpecialDefense: 100,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 151
    },
    {
        NationalNumber: 152,
        Name: "Chikorita",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 45,
        Attack: 49,
        Defense: 65,
        SpecialAttack: 49,
        SpecialDefense: 65,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 152
    },
    {
        NationalNumber: 153,
        Name: "Bayleef",
        Tier: "NU",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 60,
        Attack: 62,
        Defense: 80,
        SpecialAttack: 63,
        SpecialDefense: 80,
        Speed: 60,
        PreEvolution: "Chikorita",
        DefaultGender: "Random",
        FirstStage: 152
    },
    {
        NationalNumber: 154,
        Name: "Meganium",
        Tier: "UUBL",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 80,
        Attack: 82,
        Defense: 100,
        SpecialAttack: 83,
        SpecialDefense: 100,
        Speed: 80,
        PreEvolution: "Bayleef",
        DefaultGender: "Random",
        FirstStage: 152
    },
    {
        NationalNumber: 155,
        Name: "Cyndaquil",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 39,
        Attack: 52,
        Defense: 43,
        SpecialAttack: 60,
        SpecialDefense: 50,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 155
    },
    {
        NationalNumber: 156,
        Name: "Quilava",
        Tier: "NFE",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 58,
        Attack: 64,
        Defense: 58,
        SpecialAttack: 80,
        SpecialDefense: 65,
        Speed: 80,
        PreEvolution: "Cyndaquil",
        DefaultGender: "Random",
        FirstStage: 155
    },
    {
        NationalNumber: 157,
        Name: "Typhlosion",
        Tier: "UUBL",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 78,
        Attack: 84,
        Defense: 78,
        SpecialAttack: 109,
        SpecialDefense: 85,
        Speed: 100,
        PreEvolution: "Quilava",
        DefaultGender: "Random",
        FirstStage: 155
    },
    {
        NationalNumber: 158,
        Name: "Totodile",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 50,
        Attack: 65,
        Defense: 64,
        SpecialAttack: 44,
        SpecialDefense: 48,
        Speed: 43,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 158
    },
    {
        NationalNumber: 159,
        Name: "Croconaw",
        Tier: "NFE",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 65,
        Attack: 80,
        Defense: 80,
        SpecialAttack: 59,
        SpecialDefense: 63,
        Speed: 58,
        PreEvolution: "Totodile",
        DefaultGender: "Random",
        FirstStage: 158
    },
    {
        NationalNumber: 160,
        Name: "Feraligatr",
        Tier: "NUBL",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 85,
        Attack: 105,
        Defense: 100,
        SpecialAttack: 79,
        SpecialDefense: 83,
        Speed: 78,
        PreEvolution: "Croconaw",
        DefaultGender: "Random",
        FirstStage: 158
    },
    {
        NationalNumber: 161,
        Name: "Sentret",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 35,
        Attack: 46,
        Defense: 34,
        SpecialAttack: 35,
        SpecialDefense: 45,
        Speed: 20,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 161
    },
    {
        NationalNumber: 162,
        Name: "Furret",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 85,
        Attack: 76,
        Defense: 64,
        SpecialAttack: 45,
        SpecialDefense: 55,
        Speed: 90,
        PreEvolution: "Sentret",
        DefaultGender: "Random",
        FirstStage: 161
    },
    {
        NationalNumber: 163,
        Name: "Hoothoot",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 60,
        Attack: 30,
        Defense: 30,
        SpecialAttack: 36,
        SpecialDefense: 56,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 163
    },
    {
        NationalNumber: 164,
        Name: "Noctowl",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 100,
        Attack: 50,
        Defense: 50,
        SpecialAttack: 76,
        SpecialDefense: 96,
        Speed: 70,
        PreEvolution: "Hoothoot",
        DefaultGender: "Random",
        FirstStage: 163
    },
    {
        NationalNumber: 165,
        Name: "Ledyba",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: "Flying",
        HP: 40,
        Attack: 20,
        Defense: 30,
        SpecialAttack: 40,
        SpecialDefense: 80,
        Speed: 55,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 165
    },
    {
        NationalNumber: 166,
        Name: "Ledian",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Flying",
        HP: 55,
        Attack: 35,
        Defense: 50,
        SpecialAttack: 55,
        SpecialDefense: 110,
        Speed: 85,
        PreEvolution: "Ledyba",
        DefaultGender: "Random",
        FirstStage: 165
    },
    {
        NationalNumber: 167,
        Name: "Spinarak",
        Tier: "LC",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 40,
        Attack: 60,
        Defense: 40,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 167
    },
    {
        NationalNumber: 168,
        Name: "Ariados",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Poison",
        HP: 70,
        Attack: 90,
        Defense: 70,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 40,
        PreEvolution: "Spinarak",
        DefaultGender: "Random",
        FirstStage: 167
    },
    {
        NationalNumber: 169,
        Name: "Crobat",
        Tier: "UU",
        PrimaryType: "Poison",
        SecondaryType: "Flying",
        HP: 85,
        Attack: 90,
        Defense: 80,
        SpecialAttack: 70,
        SpecialDefense: 80,
        Speed: 130,
        PreEvolution: "Golbat",
        DefaultGender: "Random",
        FirstStage: 41
    },
    {
        NationalNumber: 170,
        Name: "Chinchou",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Electric",
        HP: 75,
        Attack: 38,
        Defense: 38,
        SpecialAttack: 56,
        SpecialDefense: 56,
        Speed: 67,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 170
    },
    {
        NationalNumber: 171,
        Name: "Lanturn",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Electric",
        HP: 125,
        Attack: 58,
        Defense: 58,
        SpecialAttack: 76,
        SpecialDefense: 76,
        Speed: 67,
        PreEvolution: "Chinchou",
        DefaultGender: "Random",
        FirstStage: 170
    },
    {
        NationalNumber: 172,
        Name: "Pichu",
        Tier: "LC",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 20,
        Attack: 40,
        Defense: 15,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 60,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 172
    },
    {
        NationalNumber: 173,
        Name: "Cleffa",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 50,
        Attack: 25,
        Defense: 28,
        SpecialAttack: 45,
        SpecialDefense: 55,
        Speed: 15,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 173
    },
    {
        NationalNumber: 174,
        Name: "Igglybuff",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: "Normal",
        HP: 90,
        Attack: 30,
        Defense: 15,
        SpecialAttack: 40,
        SpecialDefense: 20,
        Speed: 15,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 174
    },
    {
        NationalNumber: 175,
        Name: "Togepi",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 35,
        Attack: 20,
        Defense: 65,
        SpecialAttack: 40,
        SpecialDefense: 65,
        Speed: 20,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 175
    },
    {
        NationalNumber: 176,
        Name: "Togetic",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: "Flying",
        HP: 55,
        Attack: 40,
        Defense: 85,
        SpecialAttack: 80,
        SpecialDefense: 105,
        Speed: 40,
        PreEvolution: "Togepi",
        DefaultGender: "Random",
        FirstStage: 175
    },
    {
        NationalNumber: 177,
        Name: "Natu",
        Tier: "LC",
        PrimaryType: "Psychic",
        SecondaryType: "Flying",
        HP: 40,
        Attack: 50,
        Defense: 45,
        SpecialAttack: 70,
        SpecialDefense: 45,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 177
    },
    {
        NationalNumber: 178,
        Name: "Xatu",
        Tier: "NU",
        PrimaryType: "Psychic",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 75,
        Defense: 70,
        SpecialAttack: 95,
        SpecialDefense: 70,
        Speed: 95,
        PreEvolution: "Natu",
        DefaultGender: "Random",
        FirstStage: 177
    },
    {
        NationalNumber: 179,
        Name: "Mareep",
        Tier: "LC",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 55,
        Attack: 40,
        Defense: 40,
        SpecialAttack: 65,
        SpecialDefense: 45,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 179
    },
    {
        NationalNumber: 180,
        Name: "Flaaffy",
        Tier: "NU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 70,
        Attack: 55,
        Defense: 55,
        SpecialAttack: 80,
        SpecialDefense: 60,
        Speed: 45,
        PreEvolution: "Mareep",
        DefaultGender: "Random",
        FirstStage: 179
    },
    {
        NationalNumber: 181,
        Name: "Ampharos",
        Tier: "UU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 90,
        Attack: 75,
        Defense: 85,
        SpecialAttack: 115,
        SpecialDefense: 90,
        Speed: 55,
        PreEvolution: "Flaaffy",
        DefaultGender: "Random",
        FirstStage: 179
    },
    {
        NationalNumber: 182,
        Name: "Bellossom",
        Tier: "UU",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 75,
        Attack: 80,
        Defense: 95,
        SpecialAttack: 90,
        SpecialDefense: 100,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 182
    },
    {
        NationalNumber: 183,
        Name: "Marill",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: "Normal",
        HP: 70,
        Attack: 20,
        Defense: 50,
        SpecialAttack: 20,
        SpecialDefense: 50,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 183
    },
    {
        NationalNumber: 184,
        Name: "Azumarill",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Normal",
        HP: 100,
        Attack: 50,
        Defense: 80,
        SpecialAttack: 60,
        SpecialDefense: 80,
        Speed: 50,
        PreEvolution: "Marill",
        DefaultGender: "Random",
        FirstStage: 183
    },
    {
        NationalNumber: 185,
        Name: "Sudowoodo",
        Tier: "NU",
        PrimaryType: "Rock",
        SecondaryType: null,
        HP: 70,
        Attack: 100,
        Defense: 115,
        SpecialAttack: 30,
        SpecialDefense: 65,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 185
    },
    {
        NationalNumber: 186,
        Name: "Politoed",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 90,
        Attack: 75,
        Defense: 75,
        SpecialAttack: 90,
        SpecialDefense: 100,
        Speed: 70,
        PreEvolution: "Poliwhirl",
        DefaultGender: "Random",
        FirstStage: 60
    },
    {
        NationalNumber: 187,
        Name: "Hoppip",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: "Flying",
        HP: 35,
        Attack: 35,
        Defense: 40,
        SpecialAttack: 35,
        SpecialDefense: 55,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 187
    },
    {
        NationalNumber: 188,
        Name: "Skiploom",
        Tier: "NFE",
        PrimaryType: "Grass",
        SecondaryType: "Flying",
        HP: 55,
        Attack: 45,
        Defense: 50,
        SpecialAttack: 45,
        SpecialDefense: 65,
        Speed: 80,
        PreEvolution: "Hoppip",
        DefaultGender: "Random",
        FirstStage: 187
    },
    {
        NationalNumber: 189,
        Name: "Jumpluff",
        Tier: "UU",
        PrimaryType: "Grass",
        SecondaryType: "Flying",
        HP: 75,
        Attack: 55,
        Defense: 70,
        SpecialAttack: 55,
        SpecialDefense: 95,
        Speed: 110,
        PreEvolution: "Skiploom",
        DefaultGender: "Random",
        FirstStage: 187
    },
    {
        NationalNumber: 190,
        Name: "Aipom",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 55,
        Attack: 70,
        Defense: 55,
        SpecialAttack: 40,
        SpecialDefense: 55,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 190
    },
    {
        NationalNumber: 191,
        Name: "Sunkern",
        Tier: "LC",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 30,
        Attack: 30,
        Defense: 30,
        SpecialAttack: 30,
        SpecialDefense: 30,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 191
    },
    {
        NationalNumber: 192,
        Name: "Sunflora",
        Tier: "NU",
        PrimaryType: "Grass",
        SecondaryType: null,
        HP: 75,
        Attack: 75,
        Defense: 55,
        SpecialAttack: 105,
        SpecialDefense: 85,
        Speed: 30,
        PreEvolution: "Sunkern",
        DefaultGender: "Random",
        FirstStage: 191
    },
    {
        NationalNumber: 193,
        Name: "Yanma",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 65,
        Defense: 45,
        SpecialAttack: 75,
        SpecialDefense: 45,
        Speed: 95,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 193
    },
    {
        NationalNumber: 194,
        Name: "Wooper",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: "Ground",
        HP: 55,
        Attack: 45,
        Defense: 45,
        SpecialAttack: 25,
        SpecialDefense: 25,
        Speed: 15,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 194
    },
    {
        NationalNumber: 195,
        Name: "Quagsire",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Ground",
        HP: 95,
        Attack: 85,
        Defense: 85,
        SpecialAttack: 65,
        SpecialDefense: 65,
        Speed: 35,
        PreEvolution: "Wooper",
        DefaultGender: "Random",
        FirstStage: 194
    },
    {
        NationalNumber: 196,
        Name: "Espeon",
        Tier: "UUBL",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 65,
        Attack: 65,
        Defense: 60,
        SpecialAttack: 130,
        SpecialDefense: 95,
        Speed: 110,
        PreEvolution: "Eevee",
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 197,
        Name: "Umbreon",
        Tier: "OU",
        PrimaryType: "Dark",
        SecondaryType: null,
        HP: 95,
        Attack: 65,
        Defense: 110,
        SpecialAttack: 60,
        SpecialDefense: 130,
        Speed: 65,
        PreEvolution: "Eevee",
        DefaultGender: "Random",
        FirstStage: 133
    },
    {
        NationalNumber: 198,
        Name: "Murkrow",
        Tier: "NU",
        PrimaryType: "Dark",
        SecondaryType: "Flying",
        HP: 60,
        Attack: 85,
        Defense: 42,
        SpecialAttack: 85,
        SpecialDefense: 42,
        Speed: 91,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 198
    },
    {
        NationalNumber: 199,
        Name: "Slowking",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Psychic",
        HP: 95,
        Attack: 75,
        Defense: 80,
        SpecialAttack: 100,
        SpecialDefense: 110,
        Speed: 30,
        PreEvolution: "Slowbro",
        DefaultGender: "Random",
        FirstStage: 79
    },
    {
        NationalNumber: 200,
        Name: "Misdreavus",
        Tier: "OU",
        PrimaryType: "Ghost",
        SecondaryType: null,
        HP: 60,
        Attack: 60,
        Defense: 60,
        SpecialAttack: 85,
        SpecialDefense: 85,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 200
    },
    {
        NationalNumber: 201,
        Name: "Unown",
        Tier: "NU",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 48,
        Attack: 72,
        Defense: 48,
        SpecialAttack: 72,
        SpecialDefense: 48,
        Speed: 48,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 201
    },
    {
        NationalNumber: 202,
        Name: "Wobbuffet",
        Tier: "NU",
        PrimaryType: "Psychic",
        SecondaryType: null,
        HP: 190,
        Attack: 33,
        Defense: 58,
        SpecialAttack: 33,
        SpecialDefense: 58,
        Speed: 33,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 202
    },
    {
        NationalNumber: 203,
        Name: "Girafarig",
        Tier: "UU",
        PrimaryType: "Normal",
        SecondaryType: "Psychic",
        HP: 70,
        Attack: 80,
        Defense: 65,
        SpecialAttack: 90,
        SpecialDefense: 65,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 203
    },
    {
        NationalNumber: 204,
        Name: "Pineco",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: null,
        HP: 50,
        Attack: 65,
        Defense: 90,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 15,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 204
    },
    {
        NationalNumber: 205,
        Name: "Forretress",
        Tier: "OU",
        PrimaryType: "Bug",
        SecondaryType: "Steel",
        HP: 75,
        Attack: 90,
        Defense: 140,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 40,
        PreEvolution: "Pineco",
        DefaultGender: "Random",
        FirstStage: 204
    },
    {
        NationalNumber: 206,
        Name: "Dunsparce",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 100,
        Attack: 70,
        Defense: 70,
        SpecialAttack: 65,
        SpecialDefense: 65,
        Speed: 45,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 206
    },
    {
        NationalNumber: 207,
        Name: "Gligar",
        Tier: "UU",
        PrimaryType: "Ground",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 75,
        Defense: 105,
        SpecialAttack: 35,
        SpecialDefense: 65,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 207
    },
    {
        NationalNumber: 208,
        Name: "Steelix",
        Tier: "OU",
        PrimaryType: "Steel",
        SecondaryType: "Ground",
        HP: 75,
        Attack: 85,
        Defense: 200,
        SpecialAttack: 55,
        SpecialDefense: 65,
        Speed: 30,
        PreEvolution: "Onix",
        DefaultGender: "Random",
        FirstStage: 95
    },
    {
        NationalNumber: 209,
        Name: "Snubbull",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 60,
        Attack: 80,
        Defense: 50,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 30,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 209
    },
    {
        NationalNumber: 210,
        Name: "Granbull",
        Tier: "UU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 90,
        Attack: 120,
        Defense: 75,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 45,
        PreEvolution: "Snubbull",
        DefaultGender: "Random",
        FirstStage: 209
    },
    {
        NationalNumber: 211,
        Name: "Qwilfish",
        Tier: "UU",
        PrimaryType: "Water",
        SecondaryType: "Poison",
        HP: 65,
        Attack: 95,
        Defense: 75,
        SpecialAttack: 55,
        SpecialDefense: 55,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 211
    },
    {
        NationalNumber: 212,
        Name: "Scizor",
        Tier: "UUBL",
        PrimaryType: "Bug",
        SecondaryType: "Steel",
        HP: 70,
        Attack: 130,
        Defense: 100,
        SpecialAttack: 55,
        SpecialDefense: 80,
        Speed: 65,
        PreEvolution: "Scyther",
        DefaultGender: "Random",
        FirstStage: 123
    },
    {
        NationalNumber: 213,
        Name: "Shuckle",
        Tier: "NU",
        PrimaryType: "Bug",
        SecondaryType: "Rock",
        HP: 20,
        Attack: 10,
        Defense: 230,
        SpecialAttack: 10,
        SpecialDefense: 230,
        Speed: 5,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 213
    },
    {
        NationalNumber: 214,
        Name: "Heracross",
        Tier: "OU",
        PrimaryType: "Bug",
        SecondaryType: "Fighting",
        HP: 80,
        Attack: 125,
        Defense: 75,
        SpecialAttack: 40,
        SpecialDefense: 95,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 214
    },
    {
        NationalNumber: 215,
        Name: "Sneasel",
        Tier: "NU",
        PrimaryType: "Dark",
        SecondaryType: "Ice",
        HP: 55,
        Attack: 95,
        Defense: 55,
        SpecialAttack: 35,
        SpecialDefense: 75,
        Speed: 115,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 215
    },
    {
        NationalNumber: 216,
        Name: "Teddiursa",
        Tier: "LC",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 60,
        Attack: 80,
        Defense: 50,
        SpecialAttack: 50,
        SpecialDefense: 50,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 216
    },
    {
        NationalNumber: 217,
        Name: "Ursaring",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 90,
        Attack: 130,
        Defense: 75,
        SpecialAttack: 75,
        SpecialDefense: 75,
        Speed: 55,
        PreEvolution: "Teddiursa",
        DefaultGender: "Random",
        FirstStage: 216
    },
    {
        NationalNumber: 218,
        Name: "Slugma",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 40,
        Attack: 40,
        Defense: 40,
        SpecialAttack: 70,
        SpecialDefense: 40,
        Speed: 20,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 218
    },
    {
        NationalNumber: 219,
        Name: "Magcargo",
        Tier: "NU",
        PrimaryType: "Fire",
        SecondaryType: "Rock",
        HP: 50,
        Attack: 50,
        Defense: 120,
        SpecialAttack: 80,
        SpecialDefense: 80,
        Speed: 30,
        PreEvolution: "Slugma",
        DefaultGender: "Random",
        FirstStage: 218
    },
    {
        NationalNumber: 220,
        Name: "Swinub",
        Tier: "LC",
        PrimaryType: "Ice",
        SecondaryType: "Ground",
        HP: 50,
        Attack: 50,
        Defense: 40,
        SpecialAttack: 30,
        SpecialDefense: 30,
        Speed: 50,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 220
    },
    {
        NationalNumber: 221,
        Name: "Piloswine",
        Tier: "UU",
        PrimaryType: "Ice",
        SecondaryType: "Ground",
        HP: 100,
        Attack: 100,
        Defense: 80,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 50,
        PreEvolution: "Swinub",
        DefaultGender: "Random",
        FirstStage: 220
    },
    {
        NationalNumber: 222,
        Name: "Corsola",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Rock",
        HP: 55,
        Attack: 55,
        Defense: 85,
        SpecialAttack: 65,
        SpecialDefense: 85,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 222
    },
    {
        NationalNumber: 223,
        Name: "Remoraid",
        Tier: "LC",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 35,
        Attack: 65,
        Defense: 35,
        SpecialAttack: 65,
        SpecialDefense: 35,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 223
    },
    {
        NationalNumber: 224,
        Name: "Octillery",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 75,
        Attack: 105,
        Defense: 75,
        SpecialAttack: 105,
        SpecialDefense: 75,
        Speed: 45,
        PreEvolution: "Remoraid",
        DefaultGender: "Random",
        FirstStage: 223
    },
    {
        NationalNumber: 225,
        Name: "Delibird",
        Tier: "NU",
        PrimaryType: "Ice",
        SecondaryType: "Flying",
        HP: 45,
        Attack: 55,
        Defense: 45,
        SpecialAttack: 65,
        SpecialDefense: 45,
        Speed: 75,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 225
    },
    {
        NationalNumber: 226,
        Name: "Mantine",
        Tier: "NU",
        PrimaryType: "Water",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 40,
        Defense: 70,
        SpecialAttack: 80,
        SpecialDefense: 140,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 226
    },
    {
        NationalNumber: 227,
        Name: "Skarmory",
        Tier: "OU",
        PrimaryType: "Steel",
        SecondaryType: "Flying",
        HP: 65,
        Attack: 80,
        Defense: 140,
        SpecialAttack: 40,
        SpecialDefense: 70,
        Speed: 70,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 227
    },
    {
        NationalNumber: 228,
        Name: "Houndour",
        Tier: "NU",
        PrimaryType: "Dark",
        SecondaryType: "Fire",
        HP: 45,
        Attack: 60,
        Defense: 30,
        SpecialAttack: 80,
        SpecialDefense: 50,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 228
    },
    {
        NationalNumber: 229,
        Name: "Houndoom",
        Tier: "UUBL",
        PrimaryType: "Dark",
        SecondaryType: "Fire",
        HP: 75,
        Attack: 90,
        Defense: 50,
        SpecialAttack: 110,
        SpecialDefense: 80,
        Speed: 95,
        PreEvolution: "Houndour",
        DefaultGender: "Random",
        FirstStage: 228
    },
    {
        NationalNumber: 230,
        Name: "Kingdra",
        Tier: "UUBL",
        PrimaryType: "Water",
        SecondaryType: "Dragon",
        HP: 75,
        Attack: 95,
        Defense: 95,
        SpecialAttack: 95,
        SpecialDefense: 95,
        Speed: 85,
        PreEvolution: "Seadra",
        DefaultGender: "Random",
        FirstStage: 116
    },
    {
        NationalNumber: 231,
        Name: "Phanpy",
        Tier: "LC",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 90,
        Attack: 60,
        Defense: 60,
        SpecialAttack: 40,
        SpecialDefense: 40,
        Speed: 40,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 231
    },
    {
        NationalNumber: 232,
        Name: "Donphan",
        Tier: "UUBL",
        PrimaryType: "Ground",
        SecondaryType: null,
        HP: 90,
        Attack: 120,
        Defense: 120,
        SpecialAttack: 60,
        SpecialDefense: 60,
        Speed: 50,
        PreEvolution: "Phanpy",
        DefaultGender: "Random",
        FirstStage: 231
    },
    {
        NationalNumber: 233,
        Name: "Porygon2",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 85,
        Attack: 80,
        Defense: 90,
        SpecialAttack: 105,
        SpecialDefense: 95,
        Speed: 60,
        PreEvolution: "Porygon",
        DefaultGender: "Genderless",
        FirstStage: 137
    },
    {
        NationalNumber: 234,
        Name: "Stantler",
        Tier: "NU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 73,
        Attack: 95,
        Defense: 62,
        SpecialAttack: 85,
        SpecialDefense: 65,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 234
    },
    {
        NationalNumber: 235,
        Name: "Smeargle",
        Tier: "UUBL",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 55,
        Attack: 20,
        Defense: 35,
        SpecialAttack: 20,
        SpecialDefense: 45,
        Speed: 75,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 235
    },
    {
        NationalNumber: 236,
        Name: "Tyrogue",
        Tier: "LC",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 35,
        Attack: 35,
        Defense: 35,
        SpecialAttack: 35,
        SpecialDefense: 35,
        Speed: 35,
        PreEvolution: null,
        DefaultGender: "Male",
        FirstStage: 236
    },
    {
        NationalNumber: 237,
        Name: "Hitmontop",
        Tier: "NU",
        PrimaryType: "Fighting",
        SecondaryType: null,
        HP: 50,
        Attack: 95,
        Defense: 95,
        SpecialAttack: 35,
        SpecialDefense: 110,
        Speed: 70,
        PreEvolution: "Tyrogue",
        DefaultGender: "Male",
        FirstStage: 236
    },
    {
        NationalNumber: 238,
        Name: "Smoochum",
        Tier: "LC",
        PrimaryType: "Ice",
        SecondaryType: "Psychic",
        HP: 45,
        Attack: 30,
        Defense: 15,
        SpecialAttack: 85,
        SpecialDefense: 65,
        Speed: 65,
        PreEvolution: null,
        DefaultGender: "Female",
        FirstStage: 238
    },
    {
        NationalNumber: 239,
        Name: "Elekid",
        Tier: "NU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 45,
        Attack: 63,
        Defense: 37,
        SpecialAttack: 65,
        SpecialDefense: 55,
        Speed: 95,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 239
    },
    {
        NationalNumber: 240,
        Name: "Magby",
        Tier: "LC",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 45,
        Attack: 75,
        Defense: 37,
        SpecialAttack: 70,
        SpecialDefense: 55,
        Speed: 83,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 240
    },
    {
        NationalNumber: 241,
        Name: "Miltank",
        Tier: "OU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 95,
        Attack: 80,
        Defense: 105,
        SpecialAttack: 40,
        SpecialDefense: 70,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Female",
        FirstStage: 241
    },
    {
        NationalNumber: 242,
        Name: "Blissey",
        Tier: "OU",
        PrimaryType: "Normal",
        SecondaryType: null,
        HP: 255,
        Attack: 10,
        Defense: 10,
        SpecialAttack: 75,
        SpecialDefense: 135,
        Speed: 55,
        PreEvolution: "Chansey",
        DefaultGender: "Female",
        FirstStage: 113
    },
    {
        NationalNumber: 243,
        Name: "Raikou",
        Tier: "OU",
        PrimaryType: "Electric",
        SecondaryType: null,
        HP: 90,
        Attack: 85,
        Defense: 75,
        SpecialAttack: 115,
        SpecialDefense: 100,
        Speed: 115,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 243
    },
    {
        NationalNumber: 244,
        Name: "Entei",
        Tier: "UUBL",
        PrimaryType: "Fire",
        SecondaryType: null,
        HP: 115,
        Attack: 115,
        Defense: 85,
        SpecialAttack: 90,
        SpecialDefense: 75,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 244
    },
    {
        NationalNumber: 245,
        Name: "Suicune",
        Tier: "OU",
        PrimaryType: "Water",
        SecondaryType: null,
        HP: 100,
        Attack: 75,
        Defense: 115,
        SpecialAttack: 90,
        SpecialDefense: 115,
        Speed: 85,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 245
    },
    {
        NationalNumber: 246,
        Name: "Larvitar",
        Tier: "LC",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 50,
        Attack: 64,
        Defense: 50,
        SpecialAttack: 45,
        SpecialDefense: 50,
        Speed: 41,
        PreEvolution: null,
        DefaultGender: "Random",
        FirstStage: 246
    },
    {
        NationalNumber: 247,
        Name: "Pupitar",
        Tier: "NU",
        PrimaryType: "Rock",
        SecondaryType: "Ground",
        HP: 70,
        Attack: 84,
        Defense: 70,
        SpecialAttack: 65,
        SpecialDefense: 70,
        Speed: 51,
        PreEvolution: "Larvitar",
        DefaultGender: "Random",
        FirstStage: 246
    },
    {
        NationalNumber: 248,
        Name: "Tyranitar",
        Tier: "OU",
        PrimaryType: "Rock",
        SecondaryType: "Dark",
        HP: 100,
        Attack: 134,
        Defense: 110,
        SpecialAttack: 95,
        SpecialDefense: 100,
        Speed: 61,
        PreEvolution: "Pupitar",
        DefaultGender: "Random",
        FirstStage: 246
    },
    {
        NationalNumber: 249,
        Name: "Lugia",
        Tier: "Uber",
        PrimaryType: "Psychic",
        SecondaryType: "Flying",
        HP: 106,
        Attack: 90,
        Defense: 130,
        SpecialAttack: 90,
        SpecialDefense: 154,
        Speed: 110,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 249
    },
    {
        NationalNumber: 250,
        Name: "Ho-oh",
        Tier: "Uber",
        PrimaryType: "Fire",
        SecondaryType: "Flying",
        HP: 106,
        Attack: 130,
        Defense: 90,
        SpecialAttack: 110,
        SpecialDefense: 154,
        Speed: 90,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 250
    },
    {
        NationalNumber: 251,
        Name: "Celebi",
        Tier: "Uber",
        PrimaryType: "Psychic",
        SecondaryType: "Grass",
        HP: 100,
        Attack: 100,
        Defense: 100,
        SpecialAttack: 100,
        SpecialDefense: 100,
        Speed: 100,
        PreEvolution: null,
        DefaultGender: "Genderless",
        FirstStage: 251
    }
];
